### PR TITLE
doc: add examples for lexer and parser

### PR DESCRIPTION
**Pull request by sorawee**
- [Rendered doc (lexer)](https://github.com/racket/parser-tools/files/5719068/1.Lexers.pdf)
- [Rendered doc (parser)](https://github.com/racket/parser-tools/files/5719069/2.LALR.1.Parsers.pdf)

### CODE REVIEW

**Comment by mflatt** [comment]
Would it make sense to move the lexer example to either the beginning of the section or in `define-tokens`? It seems more easily overlooked at the end of the section.

**Comment by sorawee** [comment]
Thanks. I moved the examples to the beginning of the section. I also changed `racket` to `racketmodname` and fix `parser-tools/parser` -> `parser-tools/yacc` + `parser-tools/cfg-parser`.

Here's an updated [rendered doc](https://github.com/racket/parser-tools/files/5720098/1.Lexers.pdf) for the lexer.

**Comment by sorawee** [comment]
@mflatt I notice that in the parser page, `token-id` and `expr` are italicized. Is there a way to use the normal style? IIUC, `_id` italicizes an identifier, but I want the opposite.

`token-id`, in particular, is very weird, since the earlier `token-id` in the lexer page is styled correctly. I presume that's because it notices that `token-id` is bound. But why doesn't it work similarly in the parser page.

**Comment by sorawee** [comment]
I accidentally deleted my fork, so I will close this PR for now, and will resubmit a new one.

**Pull request closed without merging**
