### PR TITLE
Parser error messages by example

### PR DESCRIPTION
**Pull request by jeapostrophe**

### CODE REVIEW

**Comment by mflatt** [comment]
This is ok with me. There's apparently no test suite for `parser-tools`, but there's an `examples` directory. Would it make sense to add a small example there that also serves as a test?

**Comment by jeapostrophe** [comment]
I pushed a modification to `calc` with some examples.

**Comment by mflatt** [comment]
This change turns out to break `cfg-parser`: http://drdr.racket-lang.org/55282/racket/share/pkgs/parser-tools-lib/parser-tools/cfg-parser.rkt

It looks like the reason is that `cfg-parser` expands to use `parser` with a error handler of the form `(lambda (a b c . ignored) ....)`, so it accepts the extra argument, but the arguments that it wants get shifted.

While we could change `cfg-parser`, I worry that this incompatibility could affect other uses of `parser`. Maybe there should be a different way to accept the stack, such as a keyword argument?

**Comment by jeapostrophe** [comment]
I fixed it!

**Pull request merged**
